# Marc's Bioinformatics Toolbox...

require 'rubygems'
require 'composite_primary_keys'
require 'active_record'
require 'bio'
require 'date'
#require 'ensembl'
require 'gruff'

gem 'ruby-ensembl-api', '>=0.9.6'
require 'ensembl'


require File.dirname(__FILE__) + '/files/rfam_db.rb'
require File.dirname(__FILE__) + '/files/pfam_db.rb'
require File.dirname(__FILE__) + '/files/go_db.rb'
require File.dirname(__FILE__) + '/files/expression_db.rb'
require File.dirname(__FILE__) + '/files/mirbase_db.rb'
require File.dirname(__FILE__) + '/files/genome_compara_db.rb'

require File.dirname(__FILE__) + '/files/compara_db.rb'
require File.dirname(__FILE__) + '/files/ensembl_compara_connection.rb'
require File.dirname(__FILE__) + '/files/genome_db.rb'
require File.dirname(__FILE__) + '/files/ncrna_db.rb'
require File.dirname(__FILE__) + '/files/ncrna.rb'
require File.dirname(__FILE__) + '/files/ensembl_mixin.rb'
require File.dirname(__FILE__) + '/files/parser.rb'
require File.dirname(__FILE__) + '/files/ensembl_compara.rb'
require File.dirname(__FILE__) + '/files/tool_db.rb'
require File.dirname(__FILE__) + '/files/leca_db.rb'
#require File.dirname(__FILE__) + '/files/database_pipeline.rb'
require File.dirname(__FILE__) + '/files/extensions.rb'
#require File.dirname(__FILE__) + '/files/neanderthal_db.rb'
require File.dirname(__FILE__) + '/files/homolog_db.rb'
require File.dirname(__FILE__) + '/files/svgwriter.rb'
require File.dirname(__FILE__) + '/files/metagenome.rb'
require File.dirname(__FILE__) + '/files/taxonomy.rb'
require File.dirname(__FILE__) + '/files/eukaryote_db.rb'
